// Mechanical type contract captured before ServiceMaintenancePanel was partitioned.
import type { Component, ComputedRef, Ref } from "vue";
import type { MessageHandler } from "element-plus";
import type { HostFocusMetric } from "../HostMonitorDashboard.vue";
import type { CandidateStatus, MonitorCandidate, Provider } from "../../service-candidate-tree";
import type { MonitorAlertSettings } from "../../../shared/monitor-alerts";
import type { DirectoryDropTarget, DirectoryMoveDirection, EnvironmentLog, HostSnapshot, HostWorkspaceTab, KubernetesConfigDiscovery, MaintenanceCounts, MaintenanceDeploymentResponse, MaintenanceDirectory, MaintenancePayload, MaintenancePayloadResponse, MaintenanceServiceResponse, MaintenanceWorkspace, MonitorHost, MonitorInstallPreflight, MonitorInstallTask, MonitorInstallTaskPhase, MonitorInstallTaskStatus, ScriptAction, ScriptActionExecution, ScriptActionExecutionResult, ScriptActionIcon, ServiceItem, Deployment } from "./types";

export interface MaintenanceApi {
  "loading": Ref<boolean, boolean>;
  "saving": Ref<boolean, boolean>;
  "payload": Ref<{ canConfigure: boolean; canOperate: boolean; scriptActionsSupported: boolean; alertSettings: { enabled: boolean; hostOfflineEnabled: boolean; cpuEnabled: boolean; cpuThreshold: number; memoryEnabled: boolean; memoryThreshold: number; diskUsageEnabled: boolean; diskUsageThreshold: number; temperatureEnabled: boolean; temperatureThreshold: number; deploymentStatusEnabled: boolean; diskMissingEnabled: boolean; excludedDisks: string[]; consecutiveSamples: 2; }; services: { id: string; environmentId: string; name: string; description: string; status: "active" | "disabled"; scriptActions: { id: string; serviceId: string; deploymentId: string | null; name: string; icon: ScriptActionIcon; scriptBody?: string | undefined; createdAt: string; updatedAt: string; }[]; deployments: { id: string; serviceId: string; sshConnectionId: string | null; sshConnectionName: string; provider: Provider; externalId: string; displayName: string; origin: "discovered" | "manual"; status: CandidateStatus | "disabled"; state: string; metrics: { provider?: Provider | undefined; externalId?: string | undefined; name?: string | undefined; group?: string | undefined; status?: CandidateStatus | undefined; state?: string | undefined; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }; lastCheckedAt: string | null; connectionAvailable: boolean; host: string | null; port: number | null; username: string | null; scriptActions: { id: string; serviceId: string; deploymentId: string | null; name: string; icon: ScriptActionIcon; scriptBody?: string | undefined; createdAt: string; updatedAt: string; }[]; }[]; logIds: string[]; createdAt: string; updatedAt: string; }[]; logs: { id: string; name: string; sshConnectionId: string; connectionName: string; filePaths: string[]; }[]; hosts: { sshConnectionId: string; connectionName: string; host: string; port: number; username: string; connectionAvailable: boolean; monitorStatus: "ready" | "missing" | "error" | "unknown"; monitorOffline: boolean; agentId: string; agentVersion: string; monitorUpdateAvailable: boolean; protocolVersion: number; lastSequence: number; snapshot: { hostname: string; collectorUser?: string | undefined; operatingSystem?: string | undefined; architecture?: string | undefined; kernelVersion?: string | undefined; cpuCount: number; cpuUsedPercent: number; load1: number; load5: number; load15: number; memoryTotalBytes: number; memoryUsedBytes: number; memoryUsedPercent: number; uptimeSeconds: number; disks: { path: string; device?: string | undefined; filesystem?: string | undefined; totalBytes: number; freeBytes: number; usedBytes: number; usedPercent: number; }[]; temperatures: { chip: string; feature?: string | undefined; celsius: number; maximum?: number | undefined; critical?: number | undefined; }[]; } | null; candidates: { provider: Provider; externalId: string; name: string; group?: string | undefined; status: CandidateStatus; state: string; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }[]; kubernetesConfigs: { sourceId: string; path?: string | undefined; context?: string | undefined; cluster?: string | undefined; namespace?: string | undefined; currentContext: boolean; selected: boolean; status: "discovered" | "connected" | "error" | "unreadable" | "invalid"; candidateCount: number; error?: string | undefined; }[]; lastError: string; lastCollectedAt: string | null; lastPulledAt: string | null; installPath: string; installArchitecture: string; installManaged: boolean; installedAt: string | null; }[]; }, MaintenancePayload | { canConfigure: boolean; canOperate: boolean; scriptActionsSupported: boolean; alertSettings: { enabled: boolean; hostOfflineEnabled: boolean; cpuEnabled: boolean; cpuThreshold: number; memoryEnabled: boolean; memoryThreshold: number; diskUsageEnabled: boolean; diskUsageThreshold: number; temperatureEnabled: boolean; temperatureThreshold: number; deploymentStatusEnabled: boolean; diskMissingEnabled: boolean; excludedDisks: string[]; consecutiveSamples: 2; }; services: { id: string; environmentId: string; name: string; description: string; status: "active" | "disabled"; scriptActions: { id: string; serviceId: string; deploymentId: string | null; name: string; icon: ScriptActionIcon; scriptBody?: string | undefined; createdAt: string; updatedAt: string; }[]; deployments: { id: string; serviceId: string; sshConnectionId: string | null; sshConnectionName: string; provider: Provider; externalId: string; displayName: string; origin: "discovered" | "manual"; status: CandidateStatus | "disabled"; state: string; metrics: { provider?: Provider | undefined; externalId?: string | undefined; name?: string | undefined; group?: string | undefined; status?: CandidateStatus | undefined; state?: string | undefined; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }; lastCheckedAt: string | null; connectionAvailable: boolean; host: string | null; port: number | null; username: string | null; scriptActions: { id: string; serviceId: string; deploymentId: string | null; name: string; icon: ScriptActionIcon; scriptBody?: string | undefined; createdAt: string; updatedAt: string; }[]; }[]; logIds: string[]; createdAt: string; updatedAt: string; }[]; logs: { id: string; name: string; sshConnectionId: string; connectionName: string; filePaths: string[]; }[]; hosts: { sshConnectionId: string; connectionName: string; host: string; port: number; username: string; connectionAvailable: boolean; monitorStatus: "ready" | "missing" | "error" | "unknown"; monitorOffline: boolean; agentId: string; agentVersion: string; monitorUpdateAvailable: boolean; protocolVersion: number; lastSequence: number; snapshot: { hostname: string; collectorUser?: string | undefined; operatingSystem?: string | undefined; architecture?: string | undefined; kernelVersion?: string | undefined; cpuCount: number; cpuUsedPercent: number; load1: number; load5: number; load15: number; memoryTotalBytes: number; memoryUsedBytes: number; memoryUsedPercent: number; uptimeSeconds: number; disks: { path: string; device?: string | undefined; filesystem?: string | undefined; totalBytes: number; freeBytes: number; usedBytes: number; usedPercent: number; }[]; temperatures: { chip: string; feature?: string | undefined; celsius: number; maximum?: number | undefined; critical?: number | undefined; }[]; } | null; candidates: { provider: Provider; externalId: string; name: string; group?: string | undefined; status: CandidateStatus; state: string; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }[]; kubernetesConfigs: { sourceId: string; path?: string | undefined; context?: string | undefined; cluster?: string | undefined; namespace?: string | undefined; currentContext: boolean; selected: boolean; status: "discovered" | "connected" | "error" | "unreadable" | "invalid"; candidateCount: number; error?: string | undefined; }[]; lastError: string; lastCollectedAt: string | null; lastPulledAt: string | null; installPath: string; installArchitecture: string; installManaged: boolean; installedAt: string | null; }[]; }>;
  "selectedServiceId": Ref<string, string>;
  "selectedHostId": Ref<string, string>;
  "activeWorkspace": Ref<MaintenanceWorkspace, MaintenanceWorkspace>;
  "hostWorkspaceTab": Ref<HostWorkspaceTab, HostWorkspaceTab>;
  "hostFocusMetric": any;
  "discoveryTargetServiceId": Ref<string, string>;
  "pendingDiscoveryCandidate": Ref<{ provider: Provider; externalId: string; name: string; group?: string | undefined; status: CandidateStatus; state: string; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; } | null, MonitorCandidate | { provider: Provider; externalId: string; name: string; group?: string | undefined; status: CandidateStatus; state: string; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; } | null>;
  "creatingServiceFromDiscovery": Ref<boolean, boolean>;
  "servicePickerDialog": Ref<boolean, boolean>;
  "refreshingHosts": Ref<Set<string> & Omit<Set<string>, keyof Set<any>>, Set<string> | (Set<string> & Omit<Set<string>, keyof Set<any>>)>;
  "runningAction": Ref<string, string>;
  "serviceDialog": Ref<boolean, boolean>;
  "deploymentDialog": Ref<boolean, boolean>;
  "logDialog": Ref<boolean, boolean>;
  "kubernetesDialog": Ref<boolean, boolean>;
  "editingServiceId": Ref<string, string>;
  "editingDeploymentId": Ref<string, string>;
  "manualDeployment": Ref<boolean, boolean>;
  "savingKubernetes": Ref<boolean, boolean>;
  "refreshTimer": number | undefined;
  "serviceForm": { name: string; description: string; status: "active" | "disabled"; };
  "deploymentForm": { sshConnectionId: string; candidateKey: string; provider: Provider; externalId: string; displayName: string; origin: "discovered" | "manual"; };
  "selectedLogIds": Ref<string[], string[]>;
  "selectedKubernetesContextKeys": Ref<string[], string[]>;
  "selectedService": ComputedRef<{ id: string; environmentId: string; name: string; description: string; status: "active" | "disabled"; scriptActions: { id: string; serviceId: string; deploymentId: string | null; name: string; icon: ScriptActionIcon; scriptBody?: string | undefined; createdAt: string; updatedAt: string; }[]; deployments: { id: string; serviceId: string; sshConnectionId: string | null; sshConnectionName: string; provider: Provider; externalId: string; displayName: string; origin: "discovered" | "manual"; status: CandidateStatus | "disabled"; state: string; metrics: { provider?: Provider | undefined; externalId?: string | undefined; name?: string | undefined; group?: string | undefined; status?: CandidateStatus | undefined; state?: string | undefined; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }; lastCheckedAt: string | null; connectionAvailable: boolean; host: string | null; port: number | null; username: string | null; scriptActions: { id: string; serviceId: string; deploymentId: string | null; name: string; icon: ScriptActionIcon; scriptBody?: string | undefined; createdAt: string; updatedAt: string; }[]; }[]; logIds: string[]; createdAt: string; updatedAt: string; }>;
  "selectedHost": ComputedRef<{ sshConnectionId: string; connectionName: string; host: string; port: number; username: string; connectionAvailable: boolean; monitorStatus: "ready" | "missing" | "error" | "unknown"; monitorOffline: boolean; agentId: string; agentVersion: string; monitorUpdateAvailable: boolean; protocolVersion: number; lastSequence: number; snapshot: { hostname: string; collectorUser?: string | undefined; operatingSystem?: string | undefined; architecture?: string | undefined; kernelVersion?: string | undefined; cpuCount: number; cpuUsedPercent: number; load1: number; load5: number; load15: number; memoryTotalBytes: number; memoryUsedBytes: number; memoryUsedPercent: number; uptimeSeconds: number; disks: { path: string; device?: string | undefined; filesystem?: string | undefined; totalBytes: number; freeBytes: number; usedBytes: number; usedPercent: number; }[]; temperatures: { chip: string; feature?: string | undefined; celsius: number; maximum?: number | undefined; critical?: number | undefined; }[]; } | null; candidates: { provider: Provider; externalId: string; name: string; group?: string | undefined; status: CandidateStatus; state: string; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }[]; kubernetesConfigs: { sourceId: string; path?: string | undefined; context?: string | undefined; cluster?: string | undefined; namespace?: string | undefined; currentContext: boolean; selected: boolean; status: "discovered" | "connected" | "error" | "unreadable" | "invalid"; candidateCount: number; error?: string | undefined; }[]; lastError: string; lastCollectedAt: string | null; lastPulledAt: string | null; installPath: string; installArchitecture: string; installManaged: boolean; installedAt: string | null; }>;
  "selectedLogs": ComputedRef<{ id: string; name: string; sshConnectionId: string; connectionName: string; filePaths: string[]; }[]>;
  "hostCandidates": ComputedRef<{ provider: Provider; externalId: string; name: string; group?: string | undefined; status: CandidateStatus; state: string; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }[]>;
  "candidateOptions": ComputedRef<{ key: string; label: string; provider: Provider; externalId: string; name: string; group?: string | undefined; status: CandidateStatus; state: string; pid?: number | undefined; cpuUsedPercent?: number | undefined; memoryBytes?: number | undefined; restartCount?: number | undefined; uptimeSeconds?: number | undefined; metadata?: Record<string, unknown> | undefined; }[]>;
  "serviceSummary": ComputedRef<{ status: string; label: string; }>;
  "runningDeployments": ComputedRef<number>;
  "problemDeployments": ComputedRef<number>;
  "monitoredHosts": ComputedRef<number>;
  "offlineHosts": ComputedRef<number>;
  "unmonitoredHosts": ComputedRef<number>;
  "attentionItems": ComputedRef<{ key: string; value: number; label: string; }[]>;
  "selectedUnmanagedCount": ComputedRef<number>;
  "selectedWorstDisk": ComputedRef<{ path: string; device?: string; filesystem?: string; totalBytes: number; freeBytes: number; usedBytes: number; usedPercent: number; } | null>;
  "selectableKubernetesConfigs": ComputedRef<{ sourceId: string; path?: string | undefined; context?: string | undefined; cluster?: string | undefined; namespace?: string | undefined; currentContext: boolean; selected: boolean; status: "discovered" | "connected" | "error" | "unreadable" | "invalid"; candidateCount: number; error?: string | undefined; }[]>;
  "discoveryManagedKeys": ComputedRef<string[]>;
  "load": (silent?: boolean | undefined) => Promise<void>;
  "reload": (silent?: boolean | undefined) => Promise<void>;
  "countPhysicalMonitorHosts": (hosts: MonitorHost[]) => number;
  "fetchMaintenance": (silent?: boolean) => Promise<void>;
  "applyFocusTarget": () => void;
  "stopAutoRefresh": () => void;
  "startAutoRefresh": () => void;
  "summarizeService": (service: ServiceItem | null) => { status: string; label: string; };
  "statusLabel": (status: string) => string;
  "candidateLocationLabel": (candidate: MonitorCandidate) => string;
  "supportsMaintenanceActions": (provider: Provider) => boolean;
  "unsupportedMaintenanceActionReason": (provider: Provider) => string;
  "deploymentIdentity": (deployment: Deployment) => string;
  "kubernetesMetric": (deployment: Deployment, key: string) => number | "—";
  "kubernetesContextKey": (item: Pick<KubernetesConfigDiscovery, "sourceId" | "context">) => string;
  "kubernetesConfigStatusLabel": (item: KubernetesConfigDiscovery) => string;
  "openKubernetesConfiguration": () => void;
  "saveKubernetesConfiguration": () => Promise<void>;
  "formatPercent": (value?: number) => string;
  "formatBytes": (value?: number) => string;
  "formatDuration": (seconds?: number) => string;
  "formatTime": (value: string | null | undefined) => string;
  "formatRelativeCollected": (value: string | null | undefined) => string;
  "hostPresence": (host: MonitorHost) => { key: string; label: string; };
  "hostLiveCpu": (host: MonitorHost) => string;
  "worstDisk": (host: MonitorHost) => { path: string; device?: string; filesystem?: string; totalBytes: number; freeBytes: number; usedBytes: number; usedPercent: number; } | null;
  "metricTone": (value: number | undefined, threshold: number) => "unknown" | "critical" | "warn" | "ok";
  "hostUnmanagedCount": (host: MonitorHost) => number;
  "visualThreshold": (enabled: boolean, value: number, fallback: number) => number;
  "selectService": (id: string) => void;
  "selectHost": (id: string) => void;
  "openServiceCreate": (fromDiscovery?: boolean) => void;
  "openServiceEdit": () => void;
  "saveService": () => Promise<MessageHandler | undefined>;
  "removeService": () => Promise<void>;
  "resetDeploymentForm": () => void;
  "openDeploymentCreate": (candidate?: MonitorCandidate, host?: MonitorHost) => void;
  "assignDiscoveryTarget": (serviceId: string) => void;
  "beginCandidateEnrollment": (candidate: MonitorCandidate) => void;
  "pickServiceForDiscovery": (serviceId: string) => void;
  "createServiceFromDiscovery": () => void;
  "cancelServicePicker": () => void;
  "onServicePickerClosed": () => void;
  "discoveryPickerIntro": () => string;
  "openDeploymentEdit": (deployment: Deployment) => void;
  "saveDeployment": () => Promise<MessageHandler | undefined>;
  "removeDeployment": (deployment: Deployment) => Promise<void>;
  "openLogLinks": () => void;
  "saveLogLinks": () => Promise<void>;
  "refreshHost": (host: MonitorHost) => Promise<void>;
  "runMaintenanceAction": (deployment: Deployment, action: "start" | "stop" | "restart") => Promise<void>;
  "draggingDirectory": Ref<{ kind: MaintenanceDirectory; id: string; } | null, { kind: MaintenanceDirectory; id: string; } | { kind: MaintenanceDirectory; id: string; } | null>;
  "serviceDropTarget": Ref<{ id: string; after: boolean; } | null, DirectoryDropTarget | { id: string; after: boolean; } | null>;
  "hostDropTarget": Ref<{ id: string; after: boolean; } | null, DirectoryDropTarget | { id: string; after: boolean; } | null>;
  "savingServiceOrder": Ref<boolean, boolean>;
  "savingHostOrder": Ref<boolean, boolean>;
  "canSortDirectory": ComputedRef<boolean>;
  "directoryIds": (kind: MaintenanceDirectory) => string[];
  "orderedDirectoryItems": <T>(items: T[], orderedIds: string[], id: (item: T) => string) => T[];
  "directoryDropTarget": (kind: MaintenanceDirectory) => Ref<{ id: string; after: boolean; } | null, DirectoryDropTarget | { id: string; after: boolean; } | null>;
  "insertAfterDirectoryTarget": (event: DragEvent) => boolean;
  "startDirectoryDrag": (kind: MaintenanceDirectory, id: string, event: DragEvent) => void;
  "dragDirectoryOver": (kind: MaintenanceDirectory, id: string, event: DragEvent) => void;
  "leaveDirectoryDropTarget": (kind: MaintenanceDirectory, event: DragEvent) => void;
  "persistDirectoryOrder": (kind: MaintenanceDirectory, orderedIds: string[]) => Promise<void>;
  "dropDirectoryItem": (kind: MaintenanceDirectory, id: string, event: DragEvent) => Promise<void>;
  "endDirectoryDrag": () => void;
  "canMoveDirectoryItem": (kind: MaintenanceDirectory, id: string, direction: DirectoryMoveDirection) => boolean;
  "moveDirectoryItem": (kind: MaintenanceDirectory, id: string, direction: DirectoryMoveDirection) => Promise<void>;
  "handleDirectoryMove": (kind: MaintenanceDirectory, id: string, command: string | number | object) => void;
  "installingHosts": Ref<Set<string> & Omit<Set<string>, keyof Set<any>>, Set<string> | (Set<string> & Omit<Set<string>, keyof Set<any>>)>;
  "clearingHosts": Ref<Set<string> & Omit<Set<string>, keyof Set<any>>, Set<string> | (Set<string> & Omit<Set<string>, keyof Set<any>>)>;
  "installTask": Ref<{ id: string; environmentId: string; connectionId: string; connectionName: string; installPath: string; status: MonitorInstallTaskStatus; phase: MonitorInstallTaskPhase; progress: number; currentMessage: string; logs: { at: string; kind: "progress" | "output"; message: string; }[]; error: string; result: { monitorWarning?: string | undefined; }; createdAt: string; startedAt: string | null; completedAt: string | null; updatedAt: string; } | null, MonitorInstallTask | { id: string; environmentId: string; connectionId: string; connectionName: string; installPath: string; status: MonitorInstallTaskStatus; phase: MonitorInstallTaskPhase; progress: number; currentMessage: string; logs: { at: string; kind: "progress" | "output"; message: string; }[]; error: string; result: { monitorWarning?: string | undefined; }; createdAt: string; startedAt: string | null; completedAt: string | null; updatedAt: string; } | null>;
  "installTaskConnectionId": Ref<string, string>;
  "installProgressDialog": Ref<boolean, boolean>;
  "installTaskTimer": number | undefined;
  "notifiedInstallTasks": Set<string>;
  "selectedInstallTask": ComputedRef<{ id: string; environmentId: string; connectionId: string; connectionName: string; installPath: string; status: MonitorInstallTaskStatus; phase: MonitorInstallTaskPhase; progress: number; currentMessage: string; logs: { at: string; kind: "progress" | "output"; message: string; }[]; error: string; result: { monitorWarning?: string | undefined; }; createdAt: string; startedAt: string | null; completedAt: string | null; updatedAt: string; } | null>;
  "installTaskSteps": ComputedRef<({ phase: "preflight"; label: string; description: string; } | { phase: "package_validation"; label: string; description: string; } | { phase: "ssh_connect"; label: string; description: string; } | { phase: "staging"; label: string; description: string; } | { phase: "upload"; label: string; description: string; } | { phase: "remote_install"; label: string; description: string; } | { phase: "reconnect"; label: string; description: string; } | { phase: "initial_collect"; label: string; description: string; } | { phase: "persist"; label: string; description: string; })[]>;
  "isInstallTaskActive": (task: MonitorInstallTask | null | undefined) => boolean;
  "stopInstallTaskPolling": () => void;
  "startInstallTaskPolling": (connectionId: string) => void;
  "switchInstallTaskHost": (connectionId: string) => void;
  "refreshInstallTask": (connectionId: string, notify?: boolean) => Promise<void>;
  "openInstallProgress": (host: MonitorHost) => Promise<void>;
  "installTaskStepState": (index: number) => "active" | "error" | "pending" | "complete";
  "installTaskStatusLabel": (task: MonitorInstallTask) => string;
  "formatInstallTaskElapsed": (task: MonitorInstallTask) => string;
  "formatInstallLogTime": (value: string) => string;
  "isMonitorInstalled": (host: MonitorHost) => boolean;
  "validMonitorInstallPath": (value: string) => boolean;
  "promptMonitorInstallPath": (currentPath: string, message: string) => Promise<string | null>;
  "installMonitorOnHost": (host: MonitorHost) => Promise<void>;
  "clearMonitorData": (host: MonitorHost) => Promise<void>;
  "scriptActionIconComponents": Record<ScriptActionIcon, Component>;
  "scriptActionIconOptions": ScriptActionIcon[];
  "runningScriptActionId": Ref<string, string>;
  "scriptActionManagerDialog": Ref<boolean, boolean>;
  "scriptActionEditorOpen": Ref<boolean, boolean>;
  "scriptActionResultDialog": Ref<boolean, boolean>;
  "editingScriptActionId": Ref<string, string>;
  "scriptActionExecution": Ref<{ ok: boolean; action: { name: string; id: string; deploymentId: string | null; icon: ScriptActionIcon; }; succeeded: number; failed: number; results: { deploymentId: string; targetName: string; connectionId: string; connectionName: string; ok: boolean; exitCode: number | null; signal: string | null; durationMs: number; stdout: string; stderr: string; truncated: boolean; message: string; }[]; } | null, ScriptActionExecution | { ok: boolean; action: { name: string; id: string; deploymentId: string | null; icon: ScriptActionIcon; }; succeeded: number; failed: number; results: { deploymentId: string; targetName: string; connectionId: string; connectionName: string; ok: boolean; exitCode: number | null; signal: string | null; durationMs: number; stdout: string; stderr: string; truncated: boolean; message: string; }[]; } | null>;
  "scriptActionScope": { serviceId: string; deploymentId: string | null; label: string; };
  "scriptActionForm": { name: string; icon: ScriptActionIcon; scriptBody: string; };
  "scopedScriptActions": ComputedRef<{ id: string; serviceId: string; deploymentId: string | null; name: string; icon: ScriptActionIcon; scriptBody?: string | undefined; createdAt: string; updatedAt: string; }[]>;
  "resolveScriptActionIcon": (icon: ScriptActionIcon) => Component;
  "resetScriptActionForm": () => void;
  "beginScriptActionCreate": () => void;
  "beginScriptActionEdit": (action: ScriptAction) => void;
  "openScriptActionManager": (deployment?: Deployment | null) => void;
  "saveScriptAction": () => Promise<MessageHandler | undefined>;
  "removeScriptAction": (action: ScriptAction) => Promise<void>;
  "executeScriptAction": (action: ScriptAction) => Promise<void>;
  "formatScriptDuration": (milliseconds: number) => string;
  "scriptExecutionSummary": (execution: ScriptActionExecution) => string;
  "alertSettingsDialog": Ref<boolean, boolean>;
  "savingAlertSettings": Ref<boolean, boolean>;
  "alertSettingsForm": { enabled: boolean; hostOfflineEnabled: boolean; cpuEnabled: boolean; cpuThreshold: number; memoryEnabled: boolean; memoryThreshold: number; diskUsageEnabled: boolean; diskUsageThreshold: number; temperatureEnabled: boolean; temperatureThreshold: number; deploymentStatusEnabled: boolean; diskMissingEnabled: boolean; excludedDisks: string[]; consecutiveSamples: 2; };
  "cpuVisualThreshold": ComputedRef<number>;
  "memoryVisualThreshold": ComputedRef<number>;
  "diskVisualThreshold": ComputedRef<number>;
  "monitorDiskOptions": ComputedRef<{ key: string; label: string; }[]>;
  "openAlertSettings": () => void;
  "saveAlertSettings": () => Promise<void>;
}

