import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const monitoringView = readFileSync(new URL("../src/client/views/MonitoringView.vue", import.meta.url), "utf8");
const noc = readFileSync(new URL("../src/client/components/monitoring/NocScreen.vue", import.meta.url), "utf8");
const alertService = readFileSync(new URL("../src/client/components/monitoring/AlertServicePanel.vue", import.meta.url), "utf8");
const environment = readFileSync(new URL("../src/client/views/EnvironmentDetailView.vue", import.meta.url), "utf8");
const router = readFileSync(new URL("../src/client/router.ts", import.meta.url), "utf8");
const alerts = readFileSync(new URL("../src/client/components/MonitorAlertCenter.vue", import.meta.url), "utf8");
const hostDashboard = readFileSync(new URL("../src/client/components/HostMonitorDashboard.vue", import.meta.url), "utf8");
const hostFleet = readFileSync(new URL("../src/client/components/monitoring/HostFleetPanel.vue", import.meta.url), "utf8");
const hostEventCalendar = readFileSync(new URL("../src/client/components/monitoring/HostEventCalendar.vue", import.meta.url), "utf8");
const maintenanceDiscovery = readFileSync(new URL("../src/client/components/service-maintenance/MaintenanceDiscoveryDrawer.vue", import.meta.url), "utf8");

describe("monitoring dashboard wiring", () => {
  it("registers the global monitoring route and cancels overlapping overview requests", () => {
    expect(router).toContain('path: "/monitoring"');
    expect(monitoringView).toContain("overviewAbort?.abort()");
    expect(noc).toContain("host.probeState");
    expect(noc).toContain('"stale"');
    expect(noc).toContain("is-unmanaged");
    expect(monitoringView).toContain("document.hidden");
    expect(monitoringView).not.toContain("EnvironmentMonitoringDashboard");
    expect(monitoringView).not.toContain("DeploymentMonitorDashboard");
  });

  it("uses Fullscreen API and reduced motion for NOC", () => {
    expect(noc).toContain("requestFullscreen");
    expect(noc).toContain("fullscreenchange");
    expect(noc).toContain("prefers-reduced-motion");
    expect(noc).toContain("keydown");
  });

  it("sends host and service alerts to the monitoring dashboard", () => {
    expect(alerts).toContain('name: "monitoring"');
    expect(alerts).toContain('name: "ssh-keys"');
  });

  it("shows a GitHub-style host event heatmap in monitoring and service maintenance", () => {
    expect(alertService).toContain("mode=\"platform\"");
    expect(alertService).toContain("HostEventCalendar");
    expect(alertService).toContain("/api/v1/monitoring/events?");
    expect(alertService).toContain("系统历史数据，不受个人通知读取或清除影响");
    expect(alertService).toContain('pageSize: 5');
    expect(alertService).toContain('order: "priority"');
    expect(alertService).toContain("查看全部系统告警");
    expect(alertService).not.toContain("/api/v1/monitor-alerts");
    expect(hostEventCalendar).toContain("系统历史告警统计，不受个人通知读取或清除影响");
    expect(hostFleet).toContain("priority-host-grid");
    expect(hostFleet).toContain("probe-state-groups");
    expect(hostFleet).toContain("优先展示异常和高风险节点，未安装探针置底");
    expect(hostFleet).toContain("采集正常");
    expect(hostFleet).not.toContain("在线上报");
    expect(hostFleet).toContain("连接异常 · 待确认");
    expect(hostFleet).toContain("SSH 连接失败，无法确认是否安装探针");
    expect(hostFleet).toContain("查看该分类全部 {0} 个节点");
    expect(hostFleet).toContain("重新检测探针状态");
    expect(hostFleet).toContain("卸载监控探针");
    expect(hostFleet).toContain('probePath(host, "uninstall")');
    expect(hostFleet).toContain('method: "DELETE"');
    expect(hostFleet).not.toContain("host-pressure-score");
    expect(maintenanceDiscovery).toContain("<HostEventCalendar");
    expect(maintenanceDiscovery).toContain('command="uninstall"');
    expect(maintenanceDiscovery).toContain("uninstallMonitorOnHost");
    expect(maintenanceDiscovery).toContain("isMonitorInstalled(selectedHost) || selectedHost.installManaged");
    expect(maintenanceDiscovery).toContain("selectedHost.lastCollectedAt");
    expect(maintenanceDiscovery).toContain(':host-id="selectedHost.sshConnectionId"');
    expect(hostEventCalendar).toContain("/event-calendar?");
    expect(hostEventCalendar).toContain("/events?");
    expect(hostEventCalendar).toContain("rangeMonths");
    expect(hostEventCalendar).toContain("heatmapWeeks");
    expect(hostEventCalendar).toContain("event-calendar__week");
    expect(hostEventCalendar).toContain("day.coverageRatio < 0.8");
    expect(hostEventCalendar).toContain("event.occurrenceCount > 1");
    expect(hostEventCalendar).toContain("monitorEventCalendarCacheKey");
    expect(hostEventCalendar).toContain("cacheKeyForMonth");
    expect(hostEventCalendar).toContain("is-loading-data");
    expect(hostEventCalendar).toContain("告警数据读取失败");
    expect(hostDashboard).toContain("monitorHistoryCacheKey");
    expect(hostDashboard).toContain("cachedHistory ?? emptyHistory()");
    expect(hostDashboard).toContain('<section class="monitor-history__summary"');
    expect(hostDashboard).toContain('<div v-if="extraCharts.length" class="monitor-chart-grid">');
    expect(hostDashboard).not.toContain("showAllMetrics");
    expect(hostDashboard).not.toContain("monitor-history__more");
  });

  it("keeps the operational pages focused and exposes the NOC wallboard", () => {
    expect(monitoringView).not.toContain("loadAlerts");
    expect(monitoringView).toContain("NOC 大屏");
    expect(monitoringView).toContain("<NocScreen");
    expect(monitoringView).toContain(':environment-id="environmentId"');
    expect(monitoringView).toContain(':refresh-seconds="refreshSeconds"');
    expect(monitoringView).toContain("@exit=\"switchView('overview')\"");
    expect(monitoringView).toContain("$t('告警与服务')");
    expect(monitoringView).toContain("$t('主机节点')");
    expect(alertService).toContain("$t('重点告警事件')");
    expect(alertService).toContain("$t('服务')");
    expect(hostFleet).toContain("$t('返回主机节点')");
    expect(noc).toContain("<Teleport to=\"body\">");
    expect(noc).toContain("/api/v1/monitoring/events?");
    expect(noc).not.toContain("/api/v1/monitor-alerts");
    expect(noc).toContain("SYSTEM HISTORY · NOT PERSONAL INBOX");
    expect(noc).toContain("TELEMETRY HOST MATRIX");
    expect(noc).toContain("NETWORK THROUGHPUT");
    expect(noc).toContain("STORAGE WATERLINE");
    expect(noc).toContain("RESOURCE PRESSURE / LATEST SNAPSHOT");
    expect(noc).toContain("hasHostTelemetry");
    expect(noc).toContain(".filter((item) => item.total > 0)");
    expect(noc).toContain("不使用连接异常数据填充资源矩阵");
    expect(noc).toContain("不展示零值排行");
    expect(noc).toContain('request({ status: "active", severity: "critical", pageSize: 1 })');
    expect(noc).toContain('request({ status: "active", severity: "major", pageSize: 1 })');
    expect(noc).not.toContain("noc-wave");
    expect(monitoringView).toContain(':services="overview.services"');
    expect(monitoringView).toContain(':service-ranking="overview.serviceRanking"');
    expect(monitoringView).toContain(':problem-nodes="overview.problemNodes"');
    expect(hostDashboard).toContain("$t('前往服务维护')");
    expect(environment).toContain("workspaceQuery.maintenanceServiceId || workspaceQuery.serviceId");
    expect(environment).toContain("workspaceQuery.maintenanceHostId || workspaceQuery.hostId");
    expect(environment).toContain("@open-ssh=\"openServiceSsh\"");
    expect(environment).toContain("tab: \"ssh\", connectionId");
    expect(monitoringView).toContain('query: { tab: "maintenance", serviceId: service.id }');
    expect(monitoringView).toContain("$t('全部环境')");
    expect(monitoringView).not.toContain("environmentId: environmentId.value || firstMonitored.environmentId");
    expect(monitoringView).not.toContain("environmentId: environmentId.value || host.environmentId");
    expect(monitoringView).toContain("patchQuery({ view: \"hosts\", hostId: host?.sshConnectionId })");
    expect(monitoringView).toContain("hostId: undefined");
    expect(monitoringView).toContain("MONITORING_HOST_PAGE_SIZE");
    expect(monitoringView).toContain("hostOffset");
    expect(monitoringView).toContain("hostsOnly");
    expect(monitoringView).toContain("mergeHostPage");
    expect(monitoringView).toContain("function isMonitoringRoute()");
    expect(monitoringView).toContain("if (!isMonitoringRoute()) return;");
  });
});
