// Mechanical type contract captured before the DatabaseWorkbench implementation was partitioned.
import type { ComputedRef, Ref } from "vue";
import type { MessageHandler } from "element-plus";
import type { DatabaseNavigatorCategory, DatabaseNavigatorMenuItem, DatabaseNavigatorTarget, DatabaseObjectSource } from "../../database-navigator-menu";
import type { ShortcutActionId } from "../../../shared/keyboard-shortcuts";
import type { AgentDatabaseReadResult, AgentWorkbenchExecutionRequest } from "../../../shared/agent";
import type { SqlCompletionCatalog } from "../../sql-completion";
import type { BrowserCategory, ConnectionGroupItem, DatabaseConnection, DatabaseObject, DatabaseSearchResult, DatabaseTreeTask, FavoriteItem, HistoryItem, NavigatorCategory, NavigatorCategoryKey, NavigatorObjectClipboard, ObjectCategory, ObjectCategoryDefinition, ObjectFavoriteItem, ObjectGroupItem, OrganizationGrant, OrganizationShareDetail, QueryJob, QueryResultSet, QueryTab, SavedQueryItem, SchemaItem, TableMaintenanceOperation, UtilityCategory, WorkbenchNavigatorTarget } from "./types";
import type { DatabaseLayoutApi } from "./use-database-layout";
import type { formatBytes, sqlIdentifier, textSize } from "./format";
import type { shortcutLabel } from "../../keyboard-shortcuts";

export interface DatabaseWorkbenchApi {
  "loading": Ref<boolean, boolean>;
  "connecting": Ref<boolean, boolean>;
  "databaseSessionId": Ref<string, string>;
  "connections": Ref<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; }[], DatabaseConnection[] | { id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; }[]>;
  "connectionGroups": Ref<{ id: string; parentId: string | null; name: string; path: string; }[], ConnectionGroupItem[] | { id: string; parentId: string | null; name: string; path: string; }[]>;
  "selectedConnectionId": Ref<string, string>;
  "focusedConnectionId": Ref<string, string>;
  "connectionPaneWidth": Ref<number, number>;
  "connectionPaneVisible": Ref<boolean, boolean>;
  "explorerPaneWidth": Ref<number, number>;
  "informationPaneVisible": Ref<boolean, boolean>;
  "informationPaneTab": Ref<"general" | "ddl", "general" | "ddl">;
  "informationDdl": Ref<string, string>;
  "informationLoading": Ref<boolean, boolean>;
  "navigationFilter": Ref<"all" | "connected" | "disconnected", "all" | "connected" | "disconnected">;
  "showStarredOnly": Ref<boolean, boolean>;
  "queryResultLayout": Ref<"below" | "right", "below" | "right">;
  "queryFocused": Ref<boolean, boolean>;
  "syncDialogOpen": Ref<boolean, boolean>;
  "syncDialogMode": Ref<"data" | "structure", "data" | "structure">;
  "connectionEditorOpen": Ref<boolean, boolean>;
  "editingConnection": Ref<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null, DatabaseConnection | { id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null>;
  "copyConnectionMode": Ref<boolean, boolean>;
  "connectionProfileParentId": Ref<string, string>;
  "workbenchElement": Ref<HTMLElement | null, HTMLElement | null>;
  "schemas": Ref<{ name: string; charset: string; collation: string; }[], SchemaItem[] | { name: string; charset: string; collation: string; }[]>;
  "sqlCompletionCatalogs": Ref<Record<string, SqlCompletionCatalog>, Record<string, SqlCompletionCatalog>>;
  "sqlCompletionLoading": Set<string>;
  "expandedDatabases": Ref<Set<string> & Omit<Set<string>, keyof Set<any>>, Set<string> | (Set<string> & Omit<Set<string>, keyof Set<any>>)>;
  "expandedCategories": Ref<Set<string> & Omit<Set<string>, keyof Set<any>>, Set<string> | (Set<string> & Omit<Set<string>, keyof Set<any>>)>;
  "selectedDatabase": Ref<string, string>;
  "objects": Ref<Record<string, Partial<Record<BrowserCategory, DatabaseObject[]>>>, Record<string, Partial<Record<BrowserCategory, DatabaseObject[]>>>>;
  "objectLoading": Ref<string, string>;
  "navigatorTarget": Ref<string, string>;
  "objectSearch": Ref<string, string>;
  "objectViewMode": Ref<"details" | "diagram", "details" | "diagram">;
  "selectedObjects": Ref<Record<string, string>, Record<string, string>>;
  "connectionSearch": Ref<string, string>;
  "tabs": Ref<{ id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; }[], QueryTab[] | { id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; }[]>;
  "activeTabId": Ref<string, string>;
  "sidePanel": Ref<"" | "history" | "favorites", "" | "history" | "favorites">;
  "historyItems": Ref<{ id: string; connectionId: string; connectionName: string; database: string; sql: string; status: string; durationMs: number; rowCount: number; error: string; createdAt: string; }[], HistoryItem[] | { id: string; connectionId: string; connectionName: string; database: string; sql: string; status: string; durationMs: number; rowCount: number; error: string; createdAt: string; }[]>;
  "favorites": Ref<{ id: string; connectionId: string; database: string; name: string; sql: string; updatedAt: string; }[], FavoriteItem[] | { id: string; connectionId: string; database: string; name: string; sql: string; updatedAt: string; }[]>;
  "savedQueries": Ref<{ id: string; connectionId: string; database: string; name: string; sql: string; ownerName: string; createdAt: string; updatedAt: string; accessedAt: string; }[], SavedQueryItem[] | { id: string; connectionId: string; database: string; name: string; sql: string; ownerName: string; createdAt: string; updatedAt: string; accessedAt: string; }[]>;
  "selectedUtilityItems": Ref<Record<string, string>, Record<string, string>>;
  "objectFavorites": Ref<{ id: string; connectionId: string; connectionName: string; environmentId: string | null; engine: "mysql" | "mariadb"; host: string; port: number; targetType: "database" | "table"; database: string; table: string; updatedAt: string; }[], ObjectFavoriteItem[] | { id: string; connectionId: string; connectionName: string; environmentId: string | null; engine: "mysql" | "mariadb"; host: string; port: number; targetType: "database" | "table"; database: string; table: string; updatedAt: string; }[]>;
  "objectGroups": Ref<{ id: string; connectionId: string; database: string; category: NavigatorCategoryKey; name: string; members: { objectName: string; objectSource: string; }[]; createdAt: string; updatedAt: string; }[], ObjectGroupItem[] | { id: string; connectionId: string; database: string; category: NavigatorCategoryKey; name: string; members: { objectName: string; objectSource: string; }[]; createdAt: string; updatedAt: string; }[]>;
  "navigatorObjectClipboard": Ref<{ database: string; category: BrowserCategory; sourceCategory: ObjectCategory; name: string; ddl: string; } | null, NavigatorObjectClipboard | { database: string; category: BrowserCategory; sourceCategory: ObjectCategory; name: string; ddl: string; } | null>;
  "taskPanel": Ref<boolean, boolean>;
  "taskPanelRequest": Ref<{ id: string; type: "restore" | "list" | "transfer"; } | undefined, { id: string; type: "restore" | "list" | "transfer"; } | undefined>;
  "databaseTasks": Ref<{ id: string; type: "backup" | "restore" | "transfer" | "import"; connectionId: string | null; status: "pending" | "running" | "success" | "error" | "cancelled"; progress: number; title: string; details: Record<string, unknown>; downloadable: boolean; logs: string[]; error: string; createdAt: string; completedAt?: string | undefined; outputFilename: string | null; }[], DatabaseTreeTask[] | { id: string; type: "backup" | "restore" | "transfer" | "import"; connectionId: string | null; status: "pending" | "running" | "success" | "error" | "cancelled"; progress: number; title: string; details: Record<string, unknown>; downloadable: boolean; logs: string[]; error: string; createdAt: string; completedAt?: string | undefined; outputFilename: string | null; }[]>;
  "navigatorMenu": Ref<{ visible: boolean; x: number; y: number; target: { kind: "database" | "category" | "object"; database: string; category?: DatabaseNavigatorCategory | undefined; objectId?: string | undefined; objectName?: string | undefined; objectStatus?: string | undefined; objectSource?: DatabaseObjectSource | undefined; } | { kind: "connection"; connectionId: string; } | null; }, { visible: boolean; x: number; y: number; target: WorkbenchNavigatorTarget | null; } | { visible: boolean; x: number; y: number; target: { kind: "database" | "category" | "object"; database: string; category?: DatabaseNavigatorCategory | undefined; objectId?: string | undefined; objectName?: string | undefined; objectStatus?: string | undefined; objectSource?: DatabaseObjectSource | undefined; } | { kind: "connection"; connectionId: string; } | null; }>;
  "databaseSearchOpen": Ref<boolean, boolean>;
  "databaseSearchDatabase": Ref<string, string>;
  "databaseSearchQuery": Ref<string, string>;
  "databaseSearchSelection": Ref<string, string>;
  "connectionSearchContainer": Ref<HTMLElement | null, HTMLElement | null>;
  "objectSearchContainer": Ref<HTMLElement | null, HTMLElement | null>;
  "databaseSearchContainer": Ref<HTMLElement | null, HTMLElement | null>;
  "automationWorkspace": any;
  "modelWorkspace": any;
  "biWorkspace": any;
  "queryBuilderOpen": Ref<boolean, boolean>;
  "codeSnippetOpen": Ref<boolean, boolean>;
  "dataGenerator": Ref<{ visible: boolean; database: string; table: string; }, { visible: boolean; database: string; table: string; } | { visible: boolean; database: string; table: string; }>;
  "objectPrivilege": Ref<{ visible: boolean; database: string; objectName: string; objectType: "table" | "view" | "procedure" | "function"; }, { visible: boolean; database: string; objectName: string; objectType: "table" | "view" | "procedure" | "function"; } | { visible: boolean; database: string; objectName: string; objectType: "table" | "view" | "procedure" | "function"; }>;
  "shareDialogOpen": Ref<boolean, boolean>;
  "shareDialogLoading": Ref<boolean, boolean>;
  "shareConnection": Ref<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null, DatabaseConnection | { id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null>;
  "shareDetail": Ref<{ members: { id: string; username: string; role: "admin" | "member"; status: string; }[]; projects: { id: string; name: string; }[]; grants: { id: string; granteeType: "user" | "project"; granteeId: string; granteeName: string; resourceType: string; resourceId: string; }[]; } | null, OrganizationShareDetail | { members: { id: string; username: string; role: "admin" | "member"; status: string; }[]; projects: { id: string; name: string; }[]; grants: { id: string; granteeType: "user" | "project"; granteeId: string; granteeName: string; resourceType: string; resourceId: string; }[]; } | null>;
  "shareGrantee": Ref<string, string>;
  "collapsedConnectionGroups": Ref<Set<string> & Omit<Set<string>, keyof Set<any>>, Set<string> | (Set<string> & Omit<Set<string>, keyof Set<any>>)>;
  "collapsedConnectionIds": Ref<Set<string> & Omit<Set<string>, keyof Set<any>>, Set<string> | (Set<string> & Omit<Set<string>, keyof Set<any>>)>;
  "pollTimers": Set<number>;
  "databaseSessionPollTimer": number | undefined;
  "persistenceKey": ComputedRef<string>;
  "workbenchStyle": ComputedRef<{ "--connection-pane-width": string; "--information-pane-width": string; }>;
  "objectCategories": ObjectCategoryDefinition[];
  "categories": NavigatorCategory[];
  "selectedConnection": ComputedRef<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null>;
  "rootConnections": ComputedRef<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; }[]>;
  "selectedRootConnection": ComputedRef<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null>;
  "editingRootConnection": ComputedRef<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null>;
  "editingConnectionProfiles": ComputedRef<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; }[]>;
  "activeRootConnectionId": ComputedRef<string>;
  "activeConnectionProfiles": ComputedRef<{ id: string; name: string; }[]>;
  "databaseConnected": ComputedRef<boolean>;
  "activeTab": ComputedRef<{ id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; } | null>;
  "queryRunning": ComputedRef<boolean>;
  "continueOnQueryError": Ref<boolean, boolean>;
  "sqlEditor": Ref<{ currentStatementSql: () => string; selectedSql: () => string; openFind: () => void; } | null, { currentStatementSql(): string; selectedSql(): string; openFind(): void; } | { currentStatementSql: () => string; selectedSql: () => string; openFind: () => void; } | null>;
  "removeShortcutListener": (() => void) | undefined;
  "removeAgentDatabaseSceneProvider": (() => void) | undefined;
  "removeAgentWorkbenchExecutionProvider": (() => void) | undefined;
  "pendingAgentDatabaseExecutions": Map<string, { jobId: string; tab: QueryTab; timer: number; reject: (error: Error) => void; }>;
  "navigatorMenuItems": ComputedRef<DatabaseNavigatorMenuItem[]>;
  "favoriteConnectionIds": ComputedRef<Set<string>>;
  "filteredConnections": ComputedRef<{ id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; }[]>;
  "groupedConnections": ComputedRef<{ path: string; items: DatabaseConnection[]; }[]>;
  "visibleObjectFavorites": ComputedRef<{ id: string; connectionId: string; connectionName: string; environmentId: string | null; engine: "mysql" | "mariadb"; host: string; port: number; targetType: "database" | "table"; database: string; table: string; updatedAt: string; }[]>;
  "shareGrants": ComputedRef<{ id: string; granteeType: "user" | "project"; granteeId: string; granteeName: string; resourceType: string; resourceId: string; }[]>;
  "shareCandidates": ComputedRef<({ key: string; label: string; type: "user"; id: string; } | { key: string; label: string; type: "project"; id: string; })[]>;
  "sqlCompletionContext": ComputedRef<{ schemas: string[]; catalog: SqlCompletionCatalog | undefined; }>;
  "activeObjectItems": ComputedRef<DatabaseObject[]>;
  "databaseSearchResults": ComputedRef<DatabaseSearchResult[]>;
  "categoryKey": (database: string, category: NavigatorCategoryKey) => string;
  "categoryDefinition": (key: BrowserCategory) => ObjectCategoryDefinition;
  "isObjectCategory": (category: NavigatorCategory) => category is ObjectCategoryDefinition;
  "categoryItems": (database: string, category: NavigatorCategory) => DatabaseObject[];
  "queryFavoritesForDatabase": (database: string) => FavoriteItem[];
  "savedQueriesForDatabase": (database: string) => SavedQueryItem[];
  "databaseTaskDatabase": (task: DatabaseTreeTask) => string;
  "backupTasksForDatabase": (database: string) => DatabaseTreeTask[];
  "categoryCount": (database: string, category: NavigatorCategory) => number | string;
  "categorySelected": (database: string, category: NavigatorCategory) => boolean;
  "navigatorTargetKey": (target: DatabaseNavigatorTarget) => string;
  "objectCategoryLabel": (item: DatabaseObject, fallback: ObjectCategoryDefinition) => string;
  "objectSelectionKey": (tab: QueryTab) => string;
  "utilitySelectionKey": (database: string, category: UtilityCategory) => string;
  "selectedSavedQuery": (target: DatabaseNavigatorTarget) => SavedQueryItem | null;
  "selectedBackup": (target: DatabaseNavigatorTarget) => DatabaseTreeTask | null;
  "selectUtilityItem": (database: string, category: UtilityCategory, id: string) => void;
  "selectedObject": (tab?: { id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; } | null) => DatabaseObject | null;
  "selectedObjectInCategory": (database: string, category: BrowserCategory) => DatabaseObject | null;
  "selectObject": (tab: QueryTab, item: DatabaseObject) => void;
  "newTab": (sql?: string, database?: string, title?: string) => QueryTab;
  "registerDatabaseAgentScene": () => void;
  "databaseAgentResult": (request: AgentWorkbenchExecutionRequest & { domain: "database"; }, job: QueryJob) => AgentDatabaseReadResult;
  "executeAgentDatabaseWorkbench": (request: AgentWorkbenchExecutionRequest & { domain: "database"; }) => Promise<{ domain: "database"; requestId: string; result: AgentDatabaseReadResult; }>;
  "registerDatabaseAgentWorkbenchExecution": () => void;
  "queryTabDirty": (tab: QueryTab) => boolean;
  "toggleConnectionGroup": (path: string) => void;
  "setConnectionCollapsed": (connectionId: string, collapsed: boolean) => void;
  "connectionChildrenVisible": (connection: DatabaseConnection) => boolean;
  "handleConnectionNodeClick": (connection: DatabaseConnection) => void;
  "activeUtilityItems": ComputedRef<SavedQueryItem[] | DatabaseTreeTask[]>;
  "dataTabs": ComputedRef<{ id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; }[]>;
  "informationTitle": ComputedRef<string>;
  "informationSubtitle": ComputedRef<string>;
  "informationRows": ComputedRef<string[][]>;
  "persistWorkbenchPreferences": () => void;
  "restoreWorkbenchPreferences": () => void;
  "setConnectionPaneWidth": (value: number) => void;
  "startConnectionPaneResize": (event: PointerEvent) => void;
  "resizeConnectionPane": (delta: number) => void;
  "setExplorerPaneWidth": (value: number) => void;
  "startExplorerPaneResize": (event: PointerEvent) => void;
  "resizeExplorerPane": (delta: number) => void;
  "setConnectionPaneVisible": (value: boolean) => void;
  "setInformationPaneVisible": (value: boolean) => void;
  "setQueryResultLayout": (value: "below" | "right") => void;
  "visibleCategoryItems": (database: string, category: NavigatorCategory) => DatabaseObject[];
  "newDataTab": (database: string, table: string, readOnly: boolean) => QueryTab;
  "newCommandLine": (database?: string) => QueryTab;
  "newTableDesigner": (database: string, table?: string) => QueryTab;
  "newObjectTab": (database: string, category: NavigatorCategory) => void;
  "newUtilityTab": (database: string, category: UtilityCategory) => QueryTab;
  "newArtifactTab": (kind: "automation" | "model" | "user" | "bi") => QueryTab;
  "closeTab": (tab: QueryTab) => Promise<void>;
  "resetDatabaseWorkspace": (preserveSqlTabs?: boolean) => void;
  "load": () => Promise<void>;
  "showConnectionError": (error: unknown, fallback: string) => Promise<void>;
  "selectConnection": (connection: DatabaseConnection, useDefaultProfile?: boolean) => Promise<boolean>;
  "closeConnection": (connection: DatabaseConnection) => Promise<void>;
  "editConnection": (connection: DatabaseConnection) => void;
  "copyConnection": (connection: DatabaseConnection) => void;
  "createConnection": () => void;
  "createConnectionProfile": (connection: DatabaseConnection) => void;
  "switchConnectionProfile": (root: DatabaseConnection, profileId: string | null) => Promise<MessageHandler | undefined>;
  "refreshConnectionProfileEditor": (rootId: string, profileId?: string) => Promise<void>;
  "handleConnectionProfileAction": (action: "create" | "edit" | "duplicate" | "delete" | "set-active", profileId?: string) => Promise<void>;
  "focusConnection": (connection: DatabaseConnection) => void;
  "selectConnectionById": (connectionId: string) => void;
  "refreshConnections": () => Promise<void>;
  "updateConnectionPreference": (connection: DatabaseConnection, preference: { starred?: boolean; color?: string; }) => Promise<void>;
  "connectionUpdateBody": (connection: DatabaseConnection, connectionGroupId: string | null) => { environmentIds: string[]; connectionGroupId: string | null; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; };
  "moveConnectionToGroup": (connection: DatabaseConnection, connectionGroupId: string | null) => Promise<MessageHandler | undefined>;
  "createConnectionGroup": () => Promise<void>;
  "openConnectionShare": (connection?: { id: string; profileParentId: string | null; profileName: string; type: "database"; name: string; engine: "mysql" | "mariadb"; host: string; port: number; username: string; environmentId: string | null; environmentIds: string[]; connectionGroupId: string | null; connectionGroupPath: string | null; defaultDatabase: string; connectionMode: "tcp" | "sshTunnel" | "httpTunnel"; options: Record<string, unknown>; canManage: boolean; starred: boolean; color: string; } | null) => Promise<MessageHandler | undefined>;
  "grantSharedConnection": () => Promise<void>;
  "revokeSharedConnection": (grant: OrganizationGrant) => Promise<void>;
  "openConnectionContextMenu": (event: MouseEvent, connection: DatabaseConnection) => void;
  "deleteConnection": (connection: DatabaseConnection) => Promise<void>;
  "collapseAllNavigation": () => void;
  "refreshSchemas": () => Promise<MessageHandler | undefined>;
  "testConnection": (connection: DatabaseConnection) => Promise<void>;
  "loadDatabaseObjects": (database: string, force?: boolean) => Promise<void>;
  "loadSqlCompletionCatalog": (database: string, force?: boolean) => Promise<void>;
  "selectDatabaseNode": (database: string) => void;
  "toggleDatabase": (database: string, forceOpen?: boolean) => Promise<void>;
  "objectFavorite": (targetType: "database" | "table", database: string, table?: string) => { id: string; connectionId: string; connectionName: string; environmentId: string | null; engine: "mysql" | "mariadb"; host: string; port: number; targetType: "database" | "table"; database: string; table: string; updatedAt: string; } | undefined;
  "loadObjectFavorites": () => Promise<void>;
  "loadObjectGroups": () => Promise<void>;
  "objectGroup": (database: string, category: NavigatorCategoryKey, item: DatabaseObject | { name: string; sourceCategory?: string; }) => { id: string; connectionId: string; database: string; category: NavigatorCategoryKey; name: string; members: { objectName: string; objectSource: string; }[]; createdAt: string; updatedAt: string; } | undefined;
  "createObjectGroup": (target: DatabaseNavigatorTarget) => Promise<ObjectGroupItem | null>;
  "addNavigatorObjectToGroup": (target: DatabaseNavigatorTarget) => Promise<void>;
  "excludeNavigatorObjectFromGroup": (target: DatabaseNavigatorTarget) => Promise<MessageHandler | undefined>;
  "toggleObjectFavorite": (targetType: "database" | "table", database: string, table?: string) => Promise<void>;
  "removeObjectFavorite": (item: ObjectFavoriteItem) => Promise<void>;
  "openObjectFavorite": (item: ObjectFavoriteItem) => Promise<MessageHandler | undefined>;
  "openCategory": (database: string, category: NavigatorCategory) => Promise<void>;
  "toggleCategory": (database: string, category: NavigatorCategory) => Promise<void>;
  "openNavigatorObject": (database: string, category: NavigatorCategory, item: DatabaseObject) => Promise<void>;
  "selectNavigatorObject": (database: string, category: NavigatorCategory, item: DatabaseObject) => void;
  "showNavigatorDdl": (database: string, category: NavigatorCategory, item: DatabaseObject) => Promise<void>;
  "refreshObjectCategory": (tab: QueryTab) => Promise<void>;
  "selectedCategoryContext": () => { tab: { id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; }; category: ObjectCategoryDefinition; item: DatabaseObject | null; } | null;
  "selectedTableContext": () => { database: string; item: DatabaseObject; } | null;
  "currentTableContext": () => { database: string; item: DatabaseObject; } | null;
  "openSelectedObject": () => Promise<MessageHandler | undefined>;
  "designSelectedObject": () => Promise<MessageHandler | undefined>;
  "designSelectedTable": () => MessageHandler | undefined;
  "designCurrentTable": () => MessageHandler | undefined;
  "createObjectTemplate": (databaseName?: string, categoryKeyValue?: BrowserCategory) => void;
  "setTableDesignerDirty": (tab: QueryTab, dirty: boolean) => void;
  "handleTableDesignerSaved": (tab: QueryTab, payload: { tableName: string; existing: boolean; }) => Promise<void>;
  "waitForQueryJob": (jobId: string) => Promise<QueryJob>;
  "deleteObject": (database: string, category: ObjectCategoryDefinition, item: DatabaseObject) => Promise<MessageHandler | undefined>;
  "deleteSelectedObject": () => Promise<MessageHandler | undefined>;
  "removeTabsForDatabase": (database: string) => void;
  "clearDatabaseLocalState": (database: string) => void;
  "triggerSelectedTableAction": (type: "import" | "export", format?: "csv" | "xlsx" | "sql") => MessageHandler | undefined;
  "clearTableAction": (id: string) => void;
  "refreshUtilityTab": (tab?: { id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; } | null) => Promise<void>;
  "createFromUtilityTab": (tab?: { id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; } | null) => void;
  "closeTaskPanelRequest": (id: string) => void;
  "openTaskPanel": (database: string, type?: "restore" | "list" | "transfer") => void;
  "requireSelectedDatabase": () => string | null;
  "openGlobalCategory": (key: BrowserCategory | UtilityCategory) => Promise<void>;
  "handleGlobalTableCommand": (command: string) => void;
  "handleGlobalConnectionCommand": (command: string) => void;
  "handleGlobalQueryCommand": (command: string) => void;
  "handleGlobalBackupCommand": (command: string) => void;
  "openSyncDialog": (mode: "data" | "structure") => void;
  "handleDatabaseToolCommand": (command: string) => void;
  "loadInformationDdl": () => Promise<void>;
  "openDatabaseDictionary": (database: string) => void;
  "openTableDictionary": (database: string, table: string) => void;
  "closeDatabase": (database: string) => void;
  "editDatabaseTemplate": (database: string) => void;
  "createDatabaseTemplate": (database: string) => void;
  "deleteDatabase": (database: string) => Promise<MessageHandler | undefined>;
  "startDatabaseBackup": (database: string, includeData?: boolean) => Promise<void>;
  "runServerReload": (action: string, database?: string) => Promise<void>;
  "dumpTableStructure": (target: DatabaseNavigatorTarget) => Promise<void>;
  "reverseNavigatorTarget": (target: DatabaseNavigatorTarget) => Promise<void>;
  "createBiWorkspaceFromTarget": (target: DatabaseNavigatorTarget) => Promise<void>;
  "openObjectPrivileges": (target: DatabaseNavigatorTarget) => void;
  "openDatabaseSearch": (database: string) => Promise<void>;
  "openDatabaseSearchResult": (result?: DatabaseSearchResult) => Promise<MessageHandler | undefined>;
  "navigatorObject": (target: DatabaseNavigatorTarget) => { category: ObjectCategoryDefinition; item: DatabaseObject; } | null;
  "chooseNavigatorObject": (target: DatabaseNavigatorTarget, category: BrowserCategory) => Promise<DatabaseObject | null>;
  "openTableWizard": (target: DatabaseNavigatorTarget, type: "import" | "export", format?: "csv" | "xlsx" | "sql") => Promise<void>;
  "duplicateObjectDraft": (target: DatabaseNavigatorTarget) => Promise<MessageHandler | undefined>;
  "fetchObjectDdl": (database: string, category: ObjectCategoryDefinition, item: DatabaseObject) => Promise<string>;
  "executeDatabaseStatement": (sql: string, database: string) => Promise<QueryJob>;
  "rewriteCreateObjectName": (ddl: string, sourceCategory: ObjectCategory, database: string, newName: string) => string;
  "copyNavigatorObject": (target: DatabaseNavigatorTarget) => Promise<MessageHandler | undefined>;
  "pasteNavigatorObject": (target: DatabaseNavigatorTarget) => Promise<MessageHandler | undefined>;
  "duplicateTableDraft": (target: DatabaseNavigatorTarget, includeData: boolean) => MessageHandler | undefined;
  "tableMutationDraft": (target: DatabaseNavigatorTarget, operation: TableMaintenanceOperation, item: DatabaseObject) => void;
  "renameObjectDraft": (target: DatabaseNavigatorTarget) => Promise<MessageHandler | undefined>;
  "openNavigatorContextMenu": (event: MouseEvent, target: DatabaseNavigatorTarget) => void;
  "handleNavigatorMenuAction": (action: string) => Promise<void>;
  "showDdl": (database: string, category: ObjectCategoryDefinition, item: DatabaseObject) => Promise<MessageHandler | undefined>;
  "openObject": (database: string, category: ObjectCategoryDefinition, item: DatabaseObject) => Promise<void>;
  "runQuery": (sql?: string, tab?: { id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; } | null) => Promise<MessageHandler | undefined>;
  "pollJob": (tab: QueryTab, jobId: string) => void;
  "cancelQuery": () => Promise<void>;
  "formatSql": () => void;
  "explainSql": () => Promise<void>;
  "handleQueryRunCommand": (command: string) => void;
  "handleBuiltQuery": (sql: string, run: boolean) => void;
  "insertCodeSnippet": (sql: string) => void;
  "handleGeneratedData": (sql: string, run: boolean) => void;
  "syncSavedQueryTab": (tab: QueryTab, item: SavedQueryItem) => void;
  "saveQueryTab": (tab?: { id: string; title: string; sql: string; database: string; job: { id: string; status: "pending" | "running" | "success" | "error" | "cancelled"; durationMs?: number | undefined; error?: string | undefined; continueOnError?: boolean | undefined; resultSets: { columns: { name: string; table: string; type: number; }[]; rows: Array<Record<string, unknown>>; affectedRows: number; insertId: string | number; info: string; truncated: boolean; statement?: string | undefined; error?: string | undefined; }[]; } | null; activeResult: number; kind: "sql" | "command-line" | "data" | "objects" | "utility" | "table-design" | "automation" | "model" | "user" | "bi"; table?: string | undefined; readOnly?: boolean | undefined; category?: BrowserCategory | undefined; utilityCategory?: UtilityCategory | undefined; tableAction?: { id: string; type: "import" | "export"; format?: "csv" | "xlsx" | "sql" | undefined; } | undefined; dirty?: boolean | undefined; savedQueryId?: string | undefined; savedQuerySql?: string | undefined; savedQueryName?: string | undefined; savedQueryDatabase?: string | undefined; } | null) => Promise<boolean>;
  "openSavedQuery": (item: SavedQueryItem) => Promise<void>;
  "deleteSavedQuery": (item: SavedQueryItem) => Promise<void>;
  "duplicateSavedQuery": (item: SavedQueryItem) => Promise<void>;
  "renameSavedQuery": (item: SavedQueryItem) => Promise<void>;
  "exportSavedQuery": (item: SavedQueryItem) => void;
  "selectBrowserSqlFile": () => Promise<{ name: string; content: string; } | null>;
  "openExternalQuery": () => Promise<void>;
  "openSavedQueryExternally": (item: SavedQueryItem) => Promise<void>;
  "revealSavedQuery": (item: SavedQueryItem) => Promise<void>;
  "restoreSelectedBackup": (item: DatabaseTreeTask) => Promise<void>;
  "deleteBackupObject": (item: DatabaseTreeTask) => Promise<void>;
  "duplicateBackupObject": (item: DatabaseTreeTask) => Promise<void>;
  "renameBackupObject": (item: DatabaseTreeTask) => Promise<void>;
  "extractBackupSql": (item: DatabaseTreeTask) => Promise<void>;
  "revealBackupObject": (item: DatabaseTreeTask) => Promise<void>;
  "extractSqlFromFile": () => void;
  "addFavorite": () => Promise<void>;
  "loadHistory": () => Promise<void>;
  "loadFavorites": () => Promise<void>;
  "loadSavedQueries": () => Promise<void>;
  "loadDatabaseTasks": () => Promise<void>;
  "updateDatabaseTasks": (items: DatabaseTreeTask[]) => void;
  "openSaved": (sql: string, database: string, title: string) => void;
  "deleteFavorite": (item: FavoriteItem) => Promise<void>;
  "resultSummary": (result: QueryResultSet) => string;
  "queryResult": (tab: QueryTab) => QueryResultSet | undefined;
  "focusSearchInput": (container: HTMLElement | null) => void;
  "handleWorkbenchShortcut": (action: ShortcutActionId) => boolean;
  "handleWorkbenchKeydown": (event: KeyboardEvent) => void;
  "pollDatabaseSession": () => Promise<void>;
  "focusInitialConnection": () => Promise<void>;
  "unregisterDatabaseAgentProviders": () => void;
  "startDatabaseWorkbenchListeners": () => void;
  "disposeAgentScene": () => void;
  "disposeDatabaseWorkbench": () => void;
  "formatBytes": (value?: number) => string;
  "textSize": (value: string) => number;
  "sqlIdentifier": (value: string) => string;
  "shortcutLabel": (action: ShortcutActionId) => string;
}
