// Mechanical type contract captured before AgentFloatingWindow was partitioned.
import type { ComputedRef, Ref, ShallowRef } from "vue";
import type { MessageHandler } from "element-plus";
import type { AgentFloatingEdge, AgentFloatingPosition, AgentFloatingViewport } from "../../agent-floating-position";
import type { AgentActionRiskLevel, AgentChatMessage, AgentChatRole, AgentContextCard, AgentContextKind, AgentConversationSummary, AgentDatabaseReadResult, AgentDatabaseSqlSuggestion, AgentEntryMode, AgentExecutionPresentation, AgentJsonValue, AgentSettingsPublic, AgentSshCommandSuggestion, AgentSshDiagnosticResult, AgentSshScriptInterpreter, AgentSshScriptSuggestion, AgentStreamEvent, AgentTurnUsage, AgentVironToolApprovalSuggestion } from "../../../shared/agent";
import type { AgentSqlWriteKind } from "../../../shared/agent-write";
import type { AgentFloatingOverlayAction } from "../../../shared/agent-floating-overlay";
import type { ShortcutActionId } from "../../../shared/keyboard-shortcuts";
import type { AgentToolActivity } from "../../agent-tool-activity";
import type { AgentOverlayDragState, AgentSshSuggestionState, AgentDatabaseSuggestionState, AgentSshScriptSuggestionState, AgentVironApprovalState } from "./types";

export interface AgentFloatingApi {
  "edgeCollapsedStorageKey": string;
  "edgeStorageKey": string;
  "positionStorageKey": string;
  "desktop": boolean;
  "overlayRuntime": boolean;
  "open": Ref<boolean, boolean>;
  "viewport": Ref<{ width: number; height: number; }, AgentFloatingViewport | { width: number; height: number; }>;
  "buttonPosition": Ref<{ x: number; y: number; }, AgentFloatingPosition | { x: number; y: number; }>;
  "edgeCollapsed": Ref<boolean, boolean>;
  "snappedEdge": Ref<AgentFloatingEdge | null, AgentFloatingEdge | null>;
  "dragging": Ref<boolean, boolean>;
  "activePresentation": Ref<AgentEntryMode, AgentEntryMode>;
  "agentRoot": Ref<HTMLElement | null, HTMLElement | null>;
  "ignoreMouse": boolean;
  "overlayDragState": null;
  "visible": ComputedRef<boolean>;
  "entryMode": ComputedRef<AgentEntryMode>;
  "floatingVisible": ComputedRef<boolean>;
  "rootStyle": ComputedRef<{ left: string; top: string; }>;
  "panelAlignLeft": ComputedRef<boolean>;
  "panelBelow": ComputedRef<boolean>;
  "floatingButtonLabel": ComputedRef<string>;
  "chromeVisible": ComputedRef<boolean>;
  "currentViewport": () => AgentFloatingViewport;
  "defaultButtonPosition": (viewport: AgentFloatingViewport) => AgentFloatingPosition;
  "storedButtonPosition": (viewport: AgentFloatingViewport) => AgentFloatingPosition;
  "storedEdge": () => AgentFloatingEdge | null;
  "persistButtonPosition": () => void;
  "persistEdgeState": () => void;
  "collapseAtEdge": (edge: AgentFloatingEdge) => void;
  "expandFromEdge": () => void;
  "collapseToEdge": () => void;
  "togglePanel": () => void;
  "settleButtonDrag": () => void;
  "handleDesktopLauncherAction": (action: AgentFloatingOverlayAction) => undefined;
  "syncDesktopLauncherOverlay": () => void;
  "handleViewportResize": () => void;
  "isDialogOverlayTarget": (target: EventTarget | null) => boolean;
  "dialogOverlayOpen": () => boolean;
  "handleDocumentPointerDown": (event: PointerEvent) => void;
  "handleNativeViewPointerDown": () => void;
  "handlePointerOutside": () => void;
  "isAgentHitTarget": (target: EventTarget | null) => boolean;
  "syncIgnoreMouse": (ignore: boolean) => void;
  "handleOverlayMouseMove": (event: MouseEvent) => void;
  "currentSessionId": Ref<string, string>;
  "sessionItems": Ref<{ id: string; title: string; createdAt: string; updatedAt: string; messageCount: number; }[], AgentConversationSummary[] | { id: string; title: string; createdAt: string; updatedAt: string; messageCount: number; }[]>;
  "sessionsLoading": Ref<boolean, boolean>;
  "historyOpen": Ref<boolean, boolean>;
  "sessionsLoadSeq": number;
  "launchConversationReady": boolean;
  "loadSessionsTail": Promise<void>;
  "loadSettings": () => Promise<void>;
  "applyConversation": (conversation: { id: string; messages: AgentChatMessage[]; }, options?: { restoreQuick?: boolean; }) => void;
  "loadSessions": (options?: { startFresh?: boolean; restoreQuick?: boolean; }) => Promise<void>;
  "ensureLaunchConversation": () => Promise<void>;
  "refreshSessionList": () => Promise<void>;
  "createConversation": () => Promise<void>;
  "selectConversation": (sessionId: string) => Promise<void>;
  "renameConversation": (item: AgentConversationSummary) => Promise<void>;
  "deleteConversation": (item: AgentConversationSummary) => Promise<void>;
  "resetRunArtifacts": () => void;
  "input": Ref<string, string>;
  "composerExpanded": Ref<boolean, boolean>;
  "settings": ShallowRef<AgentSettingsPublic | null, AgentSettingsPublic | null>;
  "settingsError": Ref<string, string>;
  "loadingSettings": Ref<boolean, boolean>;
  "running": Ref<boolean, boolean>;
  "activeRunId": Ref<string, string>;
  "activeMessageId": Ref<string, string>;
  "messages": Ref<{ id: string; role: AgentChatRole; content: string; createdAt: string; durationMs?: number | undefined; usage?: { input: number; output: number; cacheRead: number; cacheWrite: number; totalTokens: number; } | undefined; }[], AgentChatMessage[] | { id: string; role: AgentChatRole; content: string; createdAt: string; durationMs?: number | undefined; usage?: { input: number; output: number; cacheRead: number; cacheWrite: number; totalTokens: number; } | undefined; }[]>;
  "contextCards": Ref<{ id: string; kind: AgentContextKind; title: string; summary: string; source: string; createdAt: string; resourceId?: string | undefined; }[], AgentContextCard[] | { id: string; kind: AgentContextKind; title: string; summary: string; source: string; createdAt: string; resourceId?: string | undefined; }[]>;
  "toolActivities": Ref<{ id: string; type: "call" | "result"; toolName: string; title: string; detail: string; }[], AgentToolActivity[] | { id: string; type: "call" | "result"; toolName: string; title: string; detail: string; }[]>;
  "addingContext": Ref<boolean, boolean>;
  "quickComposerVisible": Ref<boolean, boolean>;
  "quickBubbleIds": Ref<string[], string[]>;
  "quickBubblePrompts": Ref<Record<string, string>, Record<string, string>>;
  "quickExpandedBubbleId": Ref<string, string>;
  "quickHistoryTiled": Ref<boolean, boolean>;
  "quickBubblesHidden": Ref<boolean, boolean>;
  "scrollBody": Ref<HTMLElement | null, HTMLElement | null>;
  "composerInput": Ref<HTMLTextAreaElement | null, HTMLTextAreaElement | null>;
  "pendingQuickPrompt": string;
  "inputLimit": number;
  "configured": ComputedRef<boolean>;
  "diagnosticActive": ComputedRef<boolean>;
  "sendDisabled": ComputedRef<boolean>;
  "inputCount": ComputedRef<number>;
  "agentStatusText": ComputedRef<string>;
  "panelBodyVisible": ComputedRef<boolean>;
  "currentSessionTitle": ComputedRef<string>;
  "quickBubbles": ComputedRef<{ id: string; prompt: string; content: string; running: boolean; durationMs: number | undefined; usage: { input: number; output: number; cacheRead: number; cacheWrite: number; totalTokens: number; } | undefined; }[]>;
  "quickActionBubbleId": ComputedRef<string>;
  "sceneLabel": ComputedRef<string>;
  "displayedQuickBubbles": ComputedRef<{ id: string; prompt: string; content: string; running: boolean; durationMs: number | undefined; usage: { input: number; output: number; cacheRead: number; cacheWrite: number; totalTokens: number; } | undefined; }[]>;
  "nowIso": () => string;
  "newMessage": (role: AgentChatMessage["role"], content: string, id?: string) => AgentChatMessage;
  "restoreQuickBubblesFromHistory": (history: AgentChatMessage[]) => void;
  "collapseQuickHistoryStack": () => void;
  "hideQuickBubbles": () => void;
  "showQuickBubbles": () => void;
  "toggleQuickHistoryStack": () => void;
  "trackQuickBubble": (messageId: string, prompt: string) => void;
  "closeQuickBubble": (messageId: string) => void;
  "toggleQuickBubble": (messageId: string) => void;
  "scrollToBottom": () => void;
  "resizeComposerInput": () => void;
  "expandComposer": () => void;
  "collapseComposer": () => void;
  "quickPromptLabel": (value: string) => string;
  "scriptLineLabel": (script: string) => string;
  "currentSceneCard": () => AgentContextCard;
  "upsertContextCard": (card: AgentContextCard) => void;
  "captureCurrentScene": () => Promise<void>;
  "ensureAssistantMessage": (messageId: string) => AgentChatMessage;
  "applyTurnStats": (messageId: string, durationMs?: number, usage?: AgentTurnUsage) => void;
  "handleAgentEvent": (event: AgentStreamEvent) => void;
  "sendMessageFor": (presentation: AgentEntryMode) => Promise<void>;
  "sendMessage": () => Promise<void>;
  "sendQuickMessage": () => Promise<void> | undefined;
  "toggleQuickComposer": () => Promise<void>;
  "handleAppShortcut": (action: import("../../../shared/keyboard-shortcuts").ShortcutActionId) => void;
  "stopRun": () => Promise<void>;
  "openSettings": () => Promise<void>;
  "sshSuggestions": Ref<{ kind: "ssh-command-suggestion"; command: string; explanation: string; contextId: string; source: string; execution: "fill-only" | "confirm-read" | "confirm-write"; riskLevel?: AgentActionRiskLevel | undefined; impactPreview?: { riskLevel: "high"; reason: string; } | undefined; approval?: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; } | undefined; id: string; runId?: string | undefined; executing?: boolean | undefined; cancelling?: boolean | undefined; result?: { executionId: string; sessionId: string; connectionId: string; connectionName: string; host: string; executionTarget: "desktop-local" | "server-forwarded"; command: string; stdout: string; stderr: string; exitCode: number | null; signal: string | null; durationMs: number; truncated: boolean; redactionCount: number; presentation?: AgentExecutionPresentation | undefined; } | undefined; error?: string | undefined; }[], AgentSshSuggestionState[] | { kind: "ssh-command-suggestion"; command: string; explanation: string; contextId: string; source: string; execution: "fill-only" | "confirm-read" | "confirm-write"; riskLevel?: AgentActionRiskLevel | undefined; impactPreview?: { riskLevel: "high"; reason: string; } | undefined; approval?: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; } | undefined; id: string; runId?: string | undefined; executing?: boolean | undefined; cancelling?: boolean | undefined; result?: { executionId: string; sessionId: string; connectionId: string; connectionName: string; host: string; executionTarget: "desktop-local" | "server-forwarded"; command: string; stdout: string; stderr: string; exitCode: number | null; signal: string | null; durationMs: number; truncated: boolean; redactionCount: number; presentation?: AgentExecutionPresentation | undefined; } | undefined; error?: string | undefined; }[]>;
  "sshScriptSuggestions": Ref<{ kind: "ssh-script-suggestion"; script: string; interpreter: AgentSshScriptInterpreter; explanation: string; contextId: string; source: string; execution: "fill-only"; id: string; }[], AgentSshScriptSuggestionState[] | { kind: "ssh-script-suggestion"; script: string; interpreter: AgentSshScriptInterpreter; explanation: string; contextId: string; source: string; execution: "fill-only"; id: string; }[]>;
  "databaseSuggestions": Ref<{ kind: "database-sql-suggestion"; sql: string; explanation: string; contextId: string; source: string; execution: "fill-only" | "confirm-read" | "confirm-write"; riskLevel?: AgentActionRiskLevel | undefined; impactPreview?: { kind: AgentSqlWriteKind; riskLevel: Exclude<AgentActionRiskLevel, "low">; reason: string; targets: string[]; missingWhere: boolean; previewSql?: string | undefined; estimatedRows?: number | undefined; verificationSql?: string | undefined; } | undefined; approval?: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; } | undefined; id: string; runId?: string | undefined; executing?: boolean | undefined; cancelling?: boolean | undefined; result?: { connectionId: string; connectionName: string; database: string; sql: string; columns: string[]; rows: Array<Record<string, AgentJsonValue>>; rowCount: number; truncated: boolean; durationMs: number; presentation?: AgentExecutionPresentation | undefined; affectedRows?: number | undefined; insertId?: number | string | null | undefined; impactPreview?: { kind: AgentSqlWriteKind; riskLevel: Exclude<AgentActionRiskLevel, "low">; reason: string; targets: string[]; missingWhere: boolean; previewSql?: string | undefined; estimatedRows?: number | undefined; verificationSql?: string | undefined; } | undefined; } | undefined; error?: string | undefined; }[], AgentDatabaseSuggestionState[] | { kind: "database-sql-suggestion"; sql: string; explanation: string; contextId: string; source: string; execution: "fill-only" | "confirm-read" | "confirm-write"; riskLevel?: AgentActionRiskLevel | undefined; impactPreview?: { kind: AgentSqlWriteKind; riskLevel: Exclude<AgentActionRiskLevel, "low">; reason: string; targets: string[]; missingWhere: boolean; previewSql?: string | undefined; estimatedRows?: number | undefined; verificationSql?: string | undefined; } | undefined; approval?: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; } | undefined; id: string; runId?: string | undefined; executing?: boolean | undefined; cancelling?: boolean | undefined; result?: { connectionId: string; connectionName: string; database: string; sql: string; columns: string[]; rows: Array<Record<string, AgentJsonValue>>; rowCount: number; truncated: boolean; durationMs: number; presentation?: AgentExecutionPresentation | undefined; affectedRows?: number | undefined; insertId?: number | string | null | undefined; impactPreview?: { kind: AgentSqlWriteKind; riskLevel: Exclude<AgentActionRiskLevel, "low">; reason: string; targets: string[]; missingWhere: boolean; previewSql?: string | undefined; estimatedRows?: number | undefined; verificationSql?: string | undefined; } | undefined; } | undefined; error?: string | undefined; }[]>;
  "vironApprovals": Ref<{ title: string; kind: "viron-tool-approval"; toolName: string; riskLevel: AgentActionRiskLevel; approval: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; }; description: string; input: unknown; id: string; executing?: boolean | undefined; error?: string | undefined; }[], AgentVironApprovalState[] | { title: string; kind: "viron-tool-approval"; toolName: string; riskLevel: AgentActionRiskLevel; approval: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; }; description: string; input: unknown; id: string; executing?: boolean | undefined; error?: string | undefined; }[]>;
  "sshDiagnosticExecuting": ComputedRef<boolean>;
  "databaseDiagnosticExecuting": ComputedRef<boolean>;
  "quickSshSuggestions": ComputedRef<{ kind: "ssh-command-suggestion"; command: string; explanation: string; contextId: string; source: string; execution: "fill-only" | "confirm-read" | "confirm-write"; riskLevel?: AgentActionRiskLevel | undefined; impactPreview?: { riskLevel: "high"; reason: string; } | undefined; approval?: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; } | undefined; id: string; runId?: string | undefined; executing?: boolean | undefined; cancelling?: boolean | undefined; result?: { executionId: string; sessionId: string; connectionId: string; connectionName: string; host: string; executionTarget: "desktop-local" | "server-forwarded"; command: string; stdout: string; stderr: string; exitCode: number | null; signal: string | null; durationMs: number; truncated: boolean; redactionCount: number; presentation?: AgentExecutionPresentation | undefined; } | undefined; error?: string | undefined; }[]>;
  "quickSshScriptSuggestions": ComputedRef<{ kind: "ssh-script-suggestion"; script: string; interpreter: AgentSshScriptInterpreter; explanation: string; contextId: string; source: string; execution: "fill-only"; id: string; }[]>;
  "quickDatabaseSuggestions": ComputedRef<{ kind: "database-sql-suggestion"; sql: string; explanation: string; contextId: string; source: string; execution: "fill-only" | "confirm-read" | "confirm-write"; riskLevel?: AgentActionRiskLevel | undefined; impactPreview?: { kind: AgentSqlWriteKind; riskLevel: Exclude<AgentActionRiskLevel, "low">; reason: string; targets: string[]; missingWhere: boolean; previewSql?: string | undefined; estimatedRows?: number | undefined; verificationSql?: string | undefined; } | undefined; approval?: { runId: string; approvalId: string; step: number; maxSteps: number; deadlineAt: string; } | undefined; id: string; runId?: string | undefined; executing?: boolean | undefined; cancelling?: boolean | undefined; result?: { connectionId: string; connectionName: string; database: string; sql: string; columns: string[]; rows: Array<Record<string, AgentJsonValue>>; rowCount: number; truncated: boolean; durationMs: number; presentation?: AgentExecutionPresentation | undefined; affectedRows?: number | undefined; insertId?: number | string | null | undefined; impactPreview?: { kind: AgentSqlWriteKind; riskLevel: Exclude<AgentActionRiskLevel, "low">; reason: string; targets: string[]; missingWhere: boolean; previewSql?: string | undefined; estimatedRows?: number | undefined; verificationSql?: string | undefined; } | undefined; } | undefined; error?: string | undefined; }[]>;
  "fillSshSuggestion": (suggestion: AgentSshCommandSuggestion) => Promise<void>;
  "canFillSshSuggestion": (suggestion: AgentSshCommandSuggestion) => boolean;
  "fillSshScriptSuggestion": (suggestion: AgentSshScriptSuggestion) => Promise<void>;
  "sshSuggestionTarget": (suggestion: AgentSshCommandSuggestion) => { sessionId: string; context: AgentContextCard; } | null;
  "isExecutableSuggestion": (execution: AgentSshCommandSuggestion["execution"] | AgentDatabaseSqlSuggestion["execution"]) => boolean;
  "sshSuggestionBadge": (suggestion: AgentSshCommandSuggestion) => string;
  "databaseSuggestionBadge": (suggestion: AgentDatabaseSqlSuggestion) => string;
  "executeSshSuggestion": (suggestion: AgentSshSuggestionState) => Promise<undefined>;
  "cancelSshSuggestion": (suggestion: AgentSshSuggestionState) => Promise<void>;
  "stopActiveDiagnostic": () => Promise<void>;
  "databaseSuggestionTarget": (suggestion: AgentDatabaseSqlSuggestion) => { connectionId: string; database: string; } | null;
  "fillDatabaseSuggestion": (suggestion: AgentDatabaseSqlSuggestion) => Promise<undefined>;
  "executeDatabaseSuggestion": (suggestion: AgentDatabaseSuggestionState) => Promise<undefined>;
  "cancelDatabaseSuggestion": (suggestion: AgentDatabaseSuggestionState) => Promise<void>;
  "respondVironApproval": (item: AgentVironApprovalState, approved: boolean) => Promise<void>;
}
